version: '3.7'

services:
  database:
    image: "postgres"
    container_name: "postgres"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=keyboardcat
      - POSTGRES_DB=vocab_list
    ports:
      - "5432:5432"
    volumes:
      - database-data:/var/lib/postgresql/data
  jjb-node:
    build: ./api
    image: pacokwon/jjb-node
    ports:
      - "8000:8000"
    depends_on:
      - database

volumes:
  database-data:
