version: '3.7'

services:
  database:
    image: "postgres"
    container_name: "postgres"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=keyboardcat
      - POSTGRES_DB=vocab_list
    ports:
      - "5432:5432"
    volumes:
      - database-data:/var/lib/postgresql/data
  server:
    image: pacokwon/jjb-node
    build: ./api
    container_name: "node"
    environment:
      - POSTGRES_HOST=postgres
    volumes:
      - ./api:/app
    ports:
      - "8000:8000"
    depends_on:
      - database
  client:
    image: pacokwon/jjb-react
    build: ./client
    container_name: "react"
    volumes:
      - ./client:/app
    ports:
      - "8081:8081"
    depends_on:
      - server

volumes:
  database-data:
